name: Create release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: Set active Xcode path
        run: |
          XCODE_VERSION=$(cat versions.json | python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj["xcode"]);')
          sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app/Contents/Developer

      - name: Create canonical source directory
        run: |
          set -x
          sudo mkdir /Users/telegram
          sudo chown -R $(whoami) /Users/telegram
          cp -R $GITHUB_WORKSPACE /Users/telegram/
          mv /Users/telegram/$(basename $GITHUB_WORKSPACE) /Users/telegram/telegram-ios

      - name: Build the App
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
          PROVISIONING_PROFILE_APP_DATA: ${{ secrets.PROVISIONING_PROFILE_APP_DATA }}
          PROVISIONING_PROFILE_BROADCAST_UPLOAD_DATA: ${{ secrets.PROVISIONING_PROFILE_BROADCAST_UPLOAD_DATA }}
          PROVISIONING_PROFILE_INTENTS_DATA: ${{ secrets.PROVISIONING_PROFILE_INTENTS_DATA }}
          PROVISIONING_PROFILE_NOTIFICATION_CONTENT_DATA: ${{ secrets.PROVISIONING_PROFILE_NOTIFICATION_CONTENT_DATA }}
          PROVISIONING_PROFILE_NOTIFICATION_SERVICE_DATA: ${{ secrets.PROVISIONING_PROFILE_NOTIFICATION_SERVICE_DATA }}
          PROVISIONING_PROFILE_SHARE_DATA: ${{ secrets.PROVISIONING_PROFILE_SHARE_DATA }}
          PROVISIONING_PROFILE_WATCH_APP_DATA: ${{ secrets.PROVISIONING_PROFILE_WATCH_APP_DATA }}
          PROVISIONING_PROFILE_WATCH_EXTENSION_DATA: ${{ secrets.PROVISIONING_PROFILE_WATCH_EXTENSION_DATA }}
          PROVISIONING_PROFILE_WIDGET_DATA: ${{ secrets.PROVISIONING_PROFILE_WIDGET_DATA }}
        run: |
          set -x

          # source code paths are included in the final binary, so we need to make them stable across builds
          SOURCE_DIR=/Users/telegram/telegram-ios

          # use canonical bazel root
          BAZEL_USER_ROOT="/private/var/tmp/_bazel_telegram"

          cd $SOURCE_DIR

          BUILD_NUMBER_OFFSET="$(cat build_number_offset)"

          export APP_VERSION=$(cat versions.json | python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj["app"]);')
          export COMMIT_COUNT=$(git rev-list --count HEAD)
          export COMMIT_COUNT="$(($COMMIT_COUNT+$BUILD_NUMBER_OFFSET))"
          export BUILD_NUMBER="$COMMIT_COUNT"
          echo "BUILD_NUMBER=$(echo $BUILD_NUMBER)" >> $GITHUB_ENV
          echo "APP_VERSION=$(echo $APP_VERSION)" >> $GITHUB_ENV

          # prepare temporary keychain
          export MY_KEYCHAIN="$RUNNER_TEMP/temp.keychain"
          export MY_KEYCHAIN_PASSWORD="secret"
          security create-keychain -p "$MY_KEYCHAIN_PASSWORD" "$MY_KEYCHAIN"
          security list-keychains -d user -s "$MY_KEYCHAIN" $(security list-keychains -d user | sed s/\"//g)
          security set-keychain-settings "$MY_KEYCHAIN"
          security unlock-keychain -p "$MY_KEYCHAIN_PASSWORD" "$MY_KEYCHAIN"

          # install certificates
          SIGNING_CERTIFICATE_PATH="$RUNNER_TEMP/signing_certificate.p12"
          echo "$SIGNING_CERTIFICATE_P12_DATA" | base64 -di - > "$SIGNING_CERTIFICATE_PATH"
          security import "$SIGNING_CERTIFICATE_PATH" -k "$MY_KEYCHAIN" -P "$SIGNING_CERTIFICATE_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security
          security set-key-partition-list -S apple-tool:,apple: -k "$MY_KEYCHAIN_PASSWORD" "$MY_KEYCHAIN"

          # use the official release configuration
          rm -rf $HOME/telegram-configuration
          mkdir -p $HOME/telegram-configuration
          cp build-system/appstore-configuration.json $HOME/telegram-configuration/

          # prepare provisioning profiles
          PROVISIONING_PATH=$HOME/telegram-configuration/provisioning/profiles
          mkdir -p $PROVISIONING_PATH

          echo "$PROVISIONING_PROFILE_APP_DATA" | base64 -di - > "$PROVISIONING_PATH/Telegram.mobileprovision"
          echo "$PROVISIONING_PROFILE_BROADCAST_UPLOAD_DATA" | base64 -di - > "$PROVISIONING_PATH/BroadcastUpload.mobileprovision"
          echo "$PROVISIONING_PROFILE_INTENTS_DATA" | base64 -di - > "$PROVISIONING_PATH/Intents.mobileprovision"
          echo "$PROVISIONING_PROFILE_NOTIFICATION_CONTENT_DATA" | base64 -di - > "$PROVISIONING_PATH/NotificationContent.mobileprovision"
          echo "$PROVISIONING_PROFILE_NOTIFICATION_SERVICE_DATA" | base64 -di - > "$PROVISIONING_PATH/NotificationService.mobileprovision"
          echo "$PROVISIONING_PROFILE_SHARE_DATA" | base64 -di - > "$PROVISIONING_PATH/Share.mobileprovision"
          echo "$PROVISIONING_PROFILE_WATCH_APP_DATA" | base64 -di - > "$PROVISIONING_PATH/WatchApp.mobileprovision"
          echo "$PROVISIONING_PROFILE_WATCH_EXTENSION_DATA" | base64 -di - > "$PROVISIONING_PATH/WatchExtension.mobileprovision"
          echo "$PROVISIONING_PROFILE_WIDGET_DATA" | base64 -di - > "$PROVISIONING_PATH/Widget.mobileprovision"

          # build the app
          python3 build-system/Make/Make.py \
            --bazelUserRoot="$BAZEL_USER_ROOT" \
            build \
            --configurationPath="$HOME/telegram-configuration/appstore-configuration.json" \
            --codesigningInformationPath="$HOME/telegram-configuration/provisioning" \
            --buildNumber=$BUILD_NUMBER \
            --configuration=release_arm64

          # collect ipa
          OUTPUT_PATH="build/artifacts"
          rm -rf "$OUTPUT_PATH"
          mkdir -p "$OUTPUT_PATH"
          for f in bazel-out/applebin_ios-ios_arm*-opt-ST-*/bin/Telegram/Telegram.ipa; do
            cp "$f" $OUTPUT_PATH/
          done

          # collect dsym
          mkdir -p build/DSYMs
          for f in bazel-out/applebin_ios-ios_arm*-opt-ST-*/bin/Telegram/*.dSYM; do
            cp -R "$f" build/DSYMs/
          done
          zip -r "./$OUTPUT_PATH/Telegram.DSYMs.zip" build/DSYMs 1>/dev/null

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ env.BUILD_NUMBER }}
          release_name: Telegram ${{ env.APP_VERSION }} (${{ env.BUILD_NUMBER }})
          draft: false
          prerelease: false

      - name: Upload Release IPA
        id: upload-release-ipa 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /Users/telegram/telegram-ios/build/artifacts/Telegram.ipa
          asset_name: Telegram.ipa
          asset_content_type: application/zip

      - name: Upload Release DSYM
        id: upload-release-dsym 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /Users/telegram/telegram-ios/build/artifacts/Telegram.DSYMs.zip
          asset_name: Telegram.DSYMs.zip
          asset_content_type: application/zip

      - name: Deploy to App Store Connect
        env:
          APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
        run: |
          xcrun altool --upload-app --type ios \
            --file /Users/telegram/telegram-ios/build/artifacts/Telegram.ipa \
            --username "$APP_STORE_CONNECT_USERNAME" \
            --password "$APP_STORE_CONNECT_PASSWORD"
